services:
  app:
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    command: yarn start:dev

  postgres-db:
    environment:
      POSTGRES_DB: main_app
    ports:
      - '5433:5432'

  pgadmin:
    ports:
      - '8082:80'

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=redis:redis:6379:0:${REDIS_PASSWORD}
      - REDIS_HOST=redis
    ports:
      - '8088:8081'
    networks:
      - app-network
    depends_on:
      - redis
    env_file:
      - .env

  mqtt-broker:
    ports:
      - '1884:1883' # MQTT port for dev
      - '9002:9001' # WebSockets port for dev
