export enum UserRoleEnum {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  IOT_ADMIN = 'IOT_ADMIN',
  SALES_ADMIN = 'SALES_ADMIN',
  SALES = 'SALES',
  SERVICE_ADMIN = 'SERVICE_ADMIN',
  SERVICE_ADVISOR = 'SERVICE_ADVISOR',
  SERVICE_WEREHOUSE = 'SERVICE_WEREHOUSE',
  SERVICE_TECHNICIAN = 'SERVICE_TECHNICIAN',
  SERVICE_CASHIER = 'SERVICE_CASHIER',
  USER = 'USER',
  GUEST = 'GUEST',
}
